---
- hosts: localhost
  vars:
    source_key: "{{ playbook_dir }}/.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"

  tasks:
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/dotfiles.yml
